### ISSUE TITLE
玩我呐？少了一个模块  No module named 'lunar_python'

### ISSUE THREAD

**Issue by nibabaa** [china-testing/bazi#4]
浪费感情啊！
![微信截图_20240111001706](https://github.com/china-testing/bazi/assets/36554511/e6c28391-38d7-4041-9947-768bebabf7d9)
![微信截图_20240111001706](https://github.com/china-testing/bazi/assets/36554511/63296b16-c069-40f9-84f9-5657663a1149)

**Comment by china-testing** [comment]
看下首页说明： pip install sxtwl bidict lunar_python colorama
