### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by harry32009** [china-testing/bazi#6]
python bazi.py -g 1990 4 14 19
------------------------------------------------------------------------------------------------------------------------
男命    公历: 1990年4月14日   农历: 1990年3月19日 穿=害 上运时间：1997-05-14 命宫:己卯 胎元:辛未
 Traceback (most recent call last):
  File "bazi.py", line 272, in <module>
    print("\t", siling[zhis.month], lunar.getPrevJieQi(True), lunar.getPrevJieQi(True).getSolar().toYmdHms(),lunar.getNextJieQi(True),
KeyError: '辰'

**Comment by harry32009** [comment]
还有，33是强，但是后面weak又是true，这两个结果是不是矛盾：

 python bazi.py -g 1990 6 14 19
 
 八字强弱： 33 通常>29为强  weak: True

**Comment by yuanconghao** [comment]
<img width="702" alt="image" src="https://github.com/china-testing/bazi/assets/13481242/5910ff6f-ab72-48d4-912b-2081fa5627af">
datas内少了辰，另外数据貌似不对，应该为：
siling =  {
        "寅":"立春后七日戊土，七日丙火，其余十六日皆是甲木。 ",
        "卯":"惊蛰后十日甲木，二十日乙木。 ",
        "辰":"清明后九日乙木，三日癸水，其余十八日皆是戊土。 ",
        "巳":"立夏后五日戊土，九日庚金，其余十六日皆是丙火。 ",
        "午":"芒种后十日丙火，九日己土，其余十—日皆是丁火。 ",
        "未":"小暑后九日丁火，三日乙木，其余十八日皆是己土。 ",
        "申":"立秋后戊土十日，三日壬水，其余十七日皆是庚金。 ",
        "酉":"白露后十日庚金，二十日辛金。 ",
        "戌":"寒露后九日辛金，丁火三日，其余十八日皆是戊土。 ",
        "亥":"立冬后戊土七日，五日甲木，其余十八日皆是壬水。 ",
        "子":"大雪后十日壬水，二十日癸水。 ",
        "丑":"小寒后癸水九日，三日辛金，其余十八日皆是己土。"
}

**Comment by yuanconghao** [comment]
siling =  {
        "寅":"立春后七日戊土，七日丙火，其余十六日皆是甲木。 ",
        "卯":"惊蛰后十日甲木，二十日乙木。 ",
        "辰":"清明后九日乙木，三日癸水，其余十八日皆是戊土。 ",
        "巳":"立夏后五日戊土，九日庚金，其余十六日皆是丙火。 ",
        "午":"芒种后十日丙火，九日己土，其余十—日皆是丁火。 ",
        "未":"小暑后九日丁火，三日乙木，其余十八日皆是己土。 ",
        "申":"立秋后戊土十日，三日壬水，其余十七日皆是庚金。 ",
        "酉":"白露后十日庚金，二十日辛金。 ",
        "戌":"寒露后九日辛金，丁火三日，其余十八日皆是戊土。 ",
        "亥":"立冬后戊土七日，五日甲木，其余十八日皆是壬水。 ",
        "子":"大雪后十日壬水，二十日癸水。 ",
        "丑":"小寒后癸水九日，三日辛金，其余十八日皆是己土。"
}

**Comment by china-testing** [comment]
> 还有，33是强，但是后面weak又是true，这两个结果是不是矛盾：
> 
> python bazi.py -g 1990 6 14 19
> 
> 八字强弱： 33 通常>29为强 weak: True

两个不是一个体系，后面的weak看是否有根，前者是看十神的数量。强弱涉及根基，冲刑等，比较复杂，仅供参考，准确率80%左右，暂不全部实现
